import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const gameSource = readFileSync("game.js", "utf8");
const runtimeSource = readFileSync("src/game/core/runtime.js", "utf8");
const inputSource = readFileSync("src/game/core/input.js", "utf8");
const adapterSource = readFileSync("src/game/adapters/run-store-adapter.js", "utf8");
const mainStageSource = readFileSync("src/game/screens/main-stage-screen.js", "utf8");
const eventModalSource = readFileSync("src/game/screens/event-modal.js", "utf8");
const resourcesDrawerSource = readFileSync("src/game/screens/resources-drawer.js", "utf8");
const cultivationDrawerSource = readFileSync("src/game/screens/cultivation-drawer.js", "utf8");
const dwellingDrawerSource = readFileSync("src/game/screens/dwelling-drawer.js", "utf8");
const alchemyDrawerSource = readFileSync("src/game/screens/alchemy-drawer.js", "utf8");
const summaryModalSource = readFileSync("src/game/screens/summary-modal.js", "utf8");
const mainStageVmSource = readFileSync("src/game/view-models/main-stage.js", "utf8");
const eventVmSource = readFileSync("src/game/view-models/event-modal.js", "utf8");
const resourcesVmSource = readFileSync("src/game/view-models/resources-drawer.js", "utf8");
const cultivationVmSource = readFileSync("src/game/view-models/cultivation-drawer.js", "utf8");
const dwellingVmSource = readFileSync("src/game/view-models/dwelling-drawer.js", "utf8");
const alchemyVmSource = readFileSync("src/game/view-models/alchemy-drawer.js", "utf8");
const summaryVmSource = readFileSync("src/game/view-models/summary-modal.js", "utf8");
const storeSource = readFileSync("utils/run-store.js", "utf8");
const apiSource = readFileSync("utils/api.js", "utf8");

assert.match(gameSource, /createCanvasSurface/);
assert.match(gameSource, /createRuntime/);
assert.match(gameSource, /registerInputHandlers/);
assert.match(gameSource, /createMainStageScreen/);
assert.match(gameSource, /wx\.createCanvas/);
assert.doesNotMatch(gameSource, /WendaoDebug/);
assert.doesNotMatch(gameSource, /require\("\.\/utils\/run-store"\)/);

assert.match(runtimeSource, /createRuntime/);
assert.match(runtimeSource, /requestRender/);
assert.match(runtimeSource, /setRenderer/);

assert.match(inputSource, /registerInputHandlers/);
assert.match(inputSource, /wx\.onTouchStart/);
assert.match(inputSource, /wx\.onTouchEnd/);

assert.match(adapterSource, /getSnapshot/);
assert.match(adapterSource, /createRun/);
assert.match(adapterSource, /advanceTime/);
assert.match(adapterSource, /resolveEvent/);
assert.match(adapterSource, /breakthrough/);
assert.match(adapterSource, /buildDwellingFacility/);
assert.match(adapterSource, /upgradeDwellingFacility/);
assert.match(adapterSource, /startAlchemy/);
assert.match(adapterSource, /consumeAlchemyItem/);
assert.match(adapterSource, /rebirth/);

assert.match(mainStageSource, /buildMainStageViewModel/);
assert.match(mainStageSource, /buildEventModalViewModel/);
assert.match(mainStageSource, /buildResourcesDrawerViewModel/);
assert.match(mainStageSource, /buildCultivationDrawerViewModel/);
assert.match(mainStageSource, /buildDwellingDrawerViewModel/);
assert.match(mainStageSource, /buildAlchemyDrawerViewModel/);
assert.match(mainStageSource, /buildSummaryModalViewModel/);
assert.match(mainStageSource, /drawEventModal/);
assert.match(mainStageSource, /drawResourcesDrawer/);
assert.match(mainStageSource, /drawCultivationDrawer/);
assert.match(mainStageSource, /drawDwellingDrawer/);
assert.match(mainStageSource, /drawAlchemyDrawer/);
assert.match(mainStageSource, /drawSummaryModal/);
assert.match(mainStageSource, /adapter\.createRun/);
assert.match(mainStageSource, /adapter\.advanceTime/);
assert.match(mainStageSource, /adapter\.resolveEvent/);
assert.match(mainStageSource, /adapter\.breakthrough/);
assert.match(mainStageSource, /adapter\.buildDwellingFacility/);
assert.match(mainStageSource, /adapter\.upgradeDwellingFacility/);
assert.match(mainStageSource, /adapter\.startAlchemy/);
assert.match(mainStageSource, /adapter\.consumeAlchemyItem/);
assert.match(mainStageSource, /adapter\.rebirth/);
assert.match(mainStageSource, /label: "行囊"/);
assert.match(mainStageSource, /label: "修行"/);
assert.match(mainStageSource, /label: "洞府"/);
assert.match(mainStageSource, /label: "炼丹"/);

assert.match(eventModalSource, /wrapText/);
assert.match(eventModalSource, /disabledReason/);
assert.match(eventModalSource, /buttonSurface/);
assert.match(eventModalSource, /buttonBorder/);
assert.match(eventModalSource, /buttonText/);
assert.match(eventModalSource, /timeCostText/);
assert.doesNotMatch(eventModalSource, /themeTokens\.color\.jadeSoft/);
assert.match(resourcesDrawerSource, /drawResourcesDrawer/);
assert.match(resourcesDrawerSource, /buttonSurface/);
assert.match(resourcesDrawerSource, /buttonBorder/);
assert.match(cultivationDrawerSource, /drawCultivationDrawer/);
assert.match(cultivationDrawerSource, /buttonSurface/);
assert.match(cultivationDrawerSource, /buttonBorder/);
assert.match(dwellingDrawerSource, /drawDwellingDrawer/);
assert.match(dwellingDrawerSource, /buttonSurface/);
assert.match(dwellingDrawerSource, /buttonBorder/);
assert.match(alchemyDrawerSource, /drawAlchemyDrawer/);
assert.match(alchemyDrawerSource, /buttonSurface/);
assert.match(alchemyDrawerSource, /buttonBorder/);
assert.match(summaryModalSource, /drawSummaryModal/);
assert.match(summaryModalSource, /buttonSurface/);
assert.match(summaryModalSource, /buttonBorder/);

assert.match(mainStageVmSource, /mode: "boot"/);
assert.match(mainStageVmSource, /mode: "journey"/);
assert.match(mainStageVmSource, /mode: "event"/);
assert.match(mainStageVmSource, /mode: "summary"/);
assert.match(eventVmSource, /disabledReason/);
assert.match(resourcesVmSource, /title: "行囊"/);
assert.match(resourcesVmSource, /sell-resource/);
assert.match(resourcesVmSource, /convert-spirit-stone/);
assert.match(cultivationVmSource, /title: "修行"/);
assert.match(cultivationVmSource, /canBreakthrough/);
assert.match(dwellingVmSource, /title: "洞府"/);
assert.match(dwellingVmSource, /upgrade-facility/);
assert.match(dwellingVmSource, /build-facility/);
assert.match(alchemyVmSource, /title: "炼丹"/);
assert.match(alchemyVmSource, /start-alchemy/);
assert.doesNotMatch(alchemyVmSource, /start-alchemy-with-spring/);
assert.doesNotMatch(alchemyVmSource, /consume-item/);
assert.match(summaryVmSource, /title: "此世终卷"/);
assert.match(summaryVmSource, /rebirth/);

assert.match(storeSource, /createRun/);
assert.match(storeSource, /advanceTime/);
assert.match(storeSource, /resolveEvent\(optionId\)/);
assert.match(storeSource, /breakthrough/);
assert.match(storeSource, /buildDwellingFacility/);
assert.match(storeSource, /upgradeDwellingFacility/);
assert.match(storeSource, /startAlchemy/);
assert.match(storeSource, /consumeAlchemyItem/);
assert.match(storeSource, /rebirth/);

assert.match(apiSource, /\/api\/run\/create/);
assert.match(apiSource, /\/api\/run\/advance/);
assert.match(apiSource, /\/api\/run\/resolve/);
assert.match(apiSource, /\/api\/run\/breakthrough/);
assert.match(apiSource, /\/api\/run\/dwelling\/build/);
assert.match(apiSource, /\/api\/run\/dwelling\/upgrade/);
assert.match(apiSource, /\/api\/run\/alchemy\/start/);
assert.match(apiSource, /\/api\/run\/alchemy\/consume/);
assert.match(apiSource, /\/api\/run\/rebirth/);
