import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";

const homeWxml = readFileSync("pages/home/home.wxml", "utf8");
const eventWxml = readFileSync("pages/event/event.wxml", "utf8");
const summaryWxml = readFileSync("pages/summary/summary.wxml", "utf8");
const homeJs = readFileSync("pages/home/home.js", "utf8");
const eventPageJs = readFileSync("pages/event/event.js", "utf8");
const cultivationPageJs = readFileSync("pages/cultivation/cultivation.js", "utf8");
const dwellingPageJs = readFileSync("pages/dwelling/dwelling.js", "utf8");
const dwellingPageWxml = readFileSync("pages/dwelling/dwelling.wxml", "utf8");
const craftingPageJs = readFileSync("pages/crafting/crafting.js", "utf8");
const craftingPageWxml = readFileSync("pages/crafting/crafting.wxml", "utf8");
const summaryJs = readFileSync("pages/summary/summary.js", "utf8");
const runStoreSource = readFileSync("utils/run-store.js", "utf8");
const eventCardJs = readFileSync("components/event-card/index.js", "utf8");
const eventCardWxml = readFileSync("components/event-card/index.wxml", "utf8");
const choiceButtonListJs = readFileSync("components/choice-button-list/index.js", "utf8");
const choiceButtonListWxml = readFileSync("components/choice-button-list/index.wxml", "utf8");
const inspectionSheetJs = readFileSync("components/inspection-sheet/index.js", "utf8");
const inspectionSheetWxml = readFileSync("components/inspection-sheet/index.wxml", "utf8");
const playerStatusWxml = readFileSync("components/player-status-card/index.wxml", "utf8");
const breakthroughPanelWxml = readFileSync("components/breakthrough-panel/index.wxml", "utf8");
const dwellingPanelWxml = readFileSync("components/dwelling-bonus-panel/index.wxml", "utf8");
const runResultModalWxml = readFileSync("components/run-result-modal/index.wxml", "utf8");
const storeSource = readFileSync("utils/run-store.js", "utf8");
const apiSource = readFileSync("utils/api.js", "utf8");
const componentDir = "components";
const forbiddenSelectorPattern = /(^|\n)\s*view\s*\{/;

assert.match(homeWxml, /bindtap="createRun"/);
assert.match(homeWxml, /启程/);
assert.doesNotMatch(homeWxml, /继续启程/);
assert.doesNotMatch(homeWxml, /bindtap="advanceTime"/);
assert.doesNotMatch(homeWxml, /player-status-card/);
assert.doesNotMatch(homeWxml, /resource-bar/);
assert.doesNotMatch(homeWxml, /entry-card/);
assert.match(homeJs, /store\.createRun/);
assert.match(homeJs, /wx\.reLaunch\(\{ url: "\/pages\/event\/event" \}\)/);

assert.match(eventWxml, /inspection-sheet/);
assert.match(eventWxml, /bind:change="handleSectionChange"/);
assert.match(eventWxml, /bind:choose="handleChoice"/);
assert.match(eventWxml, /choicePattern="{{currentEvent\.choice_pattern}}"/);
assert.match(eventWxml, /bindtap="advanceTime"/);
assert.match(eventWxml, /journey-overview/);
assert.match(eventWxml, /journey-main-stage/);
assert.match(eventWxml, /journey-dock/);
assert.match(eventWxml, /已行 {{elapsedText}}/);
assert.match(eventWxml, /剩余寿元 {{lifespanText}}/);
assert.match(eventWxml, /事件结果/);
assert.match(eventWxml, /eventHistory/);
assert.match(eventWxml, /wx:key="historyKey"/);
assert.doesNotMatch(eventWxml, /wx:key="summary"/);
assert.doesNotMatch(eventWxml, /bindtap="openInspection"/);
assert.doesNotMatch(eventWxml, /player-status-card/);
assert.doesNotMatch(eventWxml, /resource-bar/);
assert.match(eventWxml, /activeSection === 'cultivation'/);
assert.match(eventWxml, /activeSection === 'resources'/);
assert.match(eventWxml, /可出售资源/);
assert.match(eventWxml, /bindtap="openSaleSheet"/);
assert.match(eventWxml, /saleSheetVisible/);
assert.match(eventWxml, /sale-sheet-mask/);
assert.match(eventWxml, /sale-sheet-panel/);
assert.match(eventWxml, /bindtap="decreaseSaleQuantity"/);
assert.match(eventWxml, /bindtap="increaseSaleQuantity"/);
assert.match(eventWxml, /bindtap="fillSaleQuantity"/);
assert.match(eventWxml, /bindtap="confirmSaleQuantity"/);
assert.match(eventWxml, /inventorySaleCards/);
assert.match(eventWxml, /breakthrough-panel/);
assert.match(eventWxml, /bind:breakthrough="attemptBreakthrough"/);
assert.match(eventWxml, /bindtap="openDwellingPage"/);
assert.match(eventWxml, /bindtap="openCraftingPage"/);
assert.match(eventPageJs, /store\.advanceTime\(\)/);
assert.match(eventPageJs, /store\.sellResource\(/);
assert.match(eventPageJs, /store\.resolveEvent\(event\.detail\.optionId\)/);
assert.match(eventPageJs, /store\.refreshRun\(\)/);
assert.match(eventPageJs, /store\.clearRun\(\)/);
assert.match(eventPageJs, /store\.breakthrough\(\)/);
assert.match(eventPageJs, /inventorySaleCards:/);
assert.match(eventPageJs, /saleSheetVisible:/);
assert.match(eventPageJs, /selectedSaleResource:/);
assert.match(eventPageJs, /saleQuantity:/);
assert.match(eventPageJs, /openSaleSheet\(/);
assert.match(eventPageJs, /confirmSaleQuantity\(/);
assert.match(eventPageJs, /获得 \$\{gainedSpiritStone\} 灵石/);
assert.match(
  eventPageJs,
  /const selectedSaleResource = this\.data\.selectedSaleResource[\s\S]*const unitPrice = Number\([\s\S]*await store\.sellResource\(resourceKey, amount\)/
);
assert.match(eventPageJs, /async attemptBreakthrough\(\)/);
assert.match(eventPageJs, /openDwellingPage\(\)/);
assert.match(eventPageJs, /openCraftingPage\(\)/);
assert.match(eventPageJs, /builtFacilityCount:/);
assert.match(eventPageJs, /dwellingLastSettlement:/);
assert.match(eventPageJs, /"破境成功"/);
assert.match(eventPageJs, /"破境未成"/);
assert.match(eventPageJs, /wx\.reLaunch\(\{ url: "\/pages\/home\/home" \}\)/);
assert.match(eventPageJs, /activeSection: "player"/);
assert.match(eventPageJs, /elapsedText:/);
assert.match(eventPageJs, /lifespanText:/);
assert.match(eventPageJs, /eventHistory:/);
assert.match(eventPageJs, /getBreakthroughRequirements/);
assert.match(eventPageJs, /breakthroughTargetSpiritStone:/);
assert.match(cultivationPageJs, /getBreakthroughRequirements/);
assert.match(cultivationPageJs, /store\.refreshRun\(\)/);
assert.match(dwellingPageJs, /store\.refreshRun\(\)/);
assert.match(dwellingPageJs, /store\.buildDwellingFacility/);
assert.match(dwellingPageJs, /store\.upgradeDwellingFacility/);
assert.match(dwellingPageJs, /returnToJourney\(\)/);
assert.match(dwellingPageJs, /activePanel:/);
assert.match(dwellingPageJs, /currentPanelIndex:/);
assert.match(dwellingPageJs, /settlementSummary:/);
assert.match(dwellingPageJs, /facilityCards:/);
assert.match(dwellingPageJs, /selectedFacilityCard:/);
assert.match(dwellingPageJs, /facilitySheetVisible:/);
assert.match(dwellingPageJs, /switchPanel\(/);
assert.match(dwellingPageJs, /handlePanelSwipe\(/);
assert.match(dwellingPageJs, /openFacilitySheet\(/);
assert.match(dwellingPageJs, /closeFacilitySheet\(/);
assert.match(dwellingPageJs, /灵石/);
assert.match(dwellingPageJs, /wx\.showToast\(/);
assert.match(dwellingPageJs, /title: action === "build" \? "建造成功" : "升级成功"/);
assert.match(dwellingPageWxml, /bindtap="buildFacility"/);
assert.match(dwellingPageWxml, /bindtap="upgradeFacility"/);
assert.match(dwellingPageWxml, /bindtap="returnToJourney"/);
assert.match(dwellingPageWxml, /bindtap="switchPanel"/);
assert.match(dwellingPageWxml, /bindtap="openFacilitySheet"/);
assert.match(dwellingPageWxml, /bindchange="handlePanelSwipe"/);
assert.match(dwellingPageWxml, /facility-sheet-mask/);
assert.match(dwellingPageWxml, /facility-sheet-panel/);
assert.match(dwellingPageWxml, /swiper/);
assert.match(dwellingPageWxml, /current="{{currentPanelIndex}}"/);
assert.doesNotMatch(dwellingPageWxml, /hero-metrics/);
assert.doesNotMatch(dwellingPageWxml, /scroll-x="{{true}}"/);
assert.doesNotMatch(dwellingPageWxml, /compact-error/);
assert.doesNotMatch(dwellingPageWxml, /wx:if="{{error}}"/);
assert.match(craftingPageJs, /store\.refreshRun\(\)/);
assert.match(craftingPageJs, /store\.startAlchemy/);
assert.match(craftingPageJs, /store\.consumeAlchemyItem/);
assert.match(craftingPageJs, /returnToJourney\(\)/);
assert.match(craftingPageJs, /activePanel:/);
assert.match(craftingPageJs, /currentPanelIndex:/);
assert.match(craftingPageJs, /recipeCards:/);
assert.match(craftingPageJs, /inventoryCards:/);
assert.match(craftingPageJs, /switchPanel\(/);
assert.match(craftingPageJs, /handlePanelSwipe\(/);
assert.match(craftingPageWxml, /alchemy_state/);
assert.match(craftingPageWxml, /bindtap="startAlchemy"/);
assert.match(craftingPageWxml, /bindtap="startAlchemyWithSpring"/);
assert.match(craftingPageWxml, /bindtap="consumeItem"/);
assert.match(craftingPageWxml, /bindtap="returnToJourney"/);
assert.match(craftingPageWxml, /bindtap="switchPanel"/);
assert.match(craftingPageWxml, /bindchange="handlePanelSwipe"/);
assert.match(craftingPageWxml, /swiper/);
assert.match(craftingPageWxml, /current="{{currentPanelIndex}}"/);
assert.match(craftingPageWxml, /scroll-x="{{true}}"/);

assert.match(summaryWxml, /run-result-modal/);
assert.match(summaryWxml, /bind:confirm="handleRebirth"/);
assert.match(summaryWxml, /转生再启/);
assert.match(summaryWxml, /此世终卷/);
assert.doesNotMatch(summaryWxml, /player-status-card/);
assert.doesNotMatch(summaryWxml, /resource-bar/);
assert.match(summaryJs, /store\.rebirth\(\)/);
assert.match(summaryJs, /wx\.reLaunch\(\{ url: "\/pages\/home\/home" \}\)/);

assert.match(storeSource, /createRun/);
assert.match(storeSource, /clearRun/);
assert.match(storeSource, /advanceTime/);
assert.match(storeSource, /sellResource/);
assert.match(storeSource, /resolveEvent\(optionId\)/);
assert.match(apiSource, /\/api\/run\/create/);
assert.match(apiSource, /\/api\/run\/advance/);
assert.match(apiSource, /\/api\/run\/resource\/sell/);
assert.match(apiSource, /option_id: optionId/);

assert.match(eventCardJs, /formatTriggerSources/);
assert.match(eventCardWxml, /event\.title_text \|\| event\.event_name/);
assert.match(eventCardWxml, /event\.body_text/);
assert.match(eventCardWxml, /event\.event_type/);
assert.match(eventCardWxml, /event\.outcome_type/);
assert.match(eventCardWxml, /event\.risk_level/);
assert.match(eventCardWxml, /triggerSourcesText/);
assert.match(eventCardWxml, /event\.status/);

assert.match(choiceButtonListJs, /optionId: event\.currentTarget\.dataset\.optionId/);
assert.match(choiceButtonListJs, /normalizeChoices/);
assert.match(choiceButtonListJs, /choicePattern/);
assert.match(choiceButtonListJs, /完成事件/);
assert.match(choiceButtonListJs, /resourceText/);
assert.match(choiceButtonListWxml, /wx:key="option_id"/);
assert.match(choiceButtonListWxml, /data-option-id="{{item\.option_id}}"/);
assert.match(choiceButtonListWxml, /item\.displayText/);
assert.doesNotMatch(choiceButtonListWxml, /item\.is_default/);
assert.match(choiceButtonListWxml, /item\.resourceText/);
assert.match(choiceButtonListWxml, /item\.is_available/);
assert.match(choiceButtonListWxml, /item\.disabled_reason/);
assert.match(choiceButtonListWxml, /disabled="{{loading \|\| !item\.is_available}}"/);

assert.match(inspectionSheetJs, /breakthroughTargetExp/);
assert.match(inspectionSheetJs, /breakthroughTargetSpiritStone/);
assert.match(inspectionSheetWxml, /命牌/);
assert.match(inspectionSheetWxml, /行囊/);
assert.match(inspectionSheetWxml, /修炼/);
assert.match(inspectionSheetWxml, /洞府/);
assert.doesNotMatch(inspectionSheetWxml, /info-grid/);
assert.doesNotMatch(inspectionSheetWxml, /info-card/);
assert.doesNotMatch(inspectionSheetWxml, /player\.lifespan_current/);
assert.match(runStoreSource, /eventHistory/);
assert.match(runStoreSource, /pushEventHistory/);
assert.match(runStoreSource, /historyKey/);
assert.match(runStoreSource, /buildImpactLines/);
assert.match(runResultModalWxml, /actionText/);
assert.match(playerStatusWxml, /realm_display_name \|\| player\.realm/);
assert.match(breakthroughPanelWxml, /realm_display_name \|\| player\.realm/);
assert.match(breakthroughPanelWxml, /breakthroughTargetExp/);
assert.match(breakthroughPanelWxml, /breakthroughTargetSpiritStone/);
assert.match(dwellingPanelWxml, /facility\.facility_id/);
assert.match(dwellingPanelWxml, /facility\.monthly_resource_yields/);
assert.match(dwellingPanelWxml, /facility\.next_upgrade_cost/);

for (const entry of readdirSync(componentDir, { withFileTypes: true })) {
  if (!entry.isDirectory()) {
    continue;
  }

  const wxssPath = path.join(componentDir, entry.name, "index.wxss");
  const wxssSource = readFileSync(wxssPath, "utf8");
  assert.doesNotMatch(
    wxssSource,
    forbiddenSelectorPattern,
    `${wxssPath} should not use tag-name selectors in component WXSS`
  );
}
